CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE NOTA_FISCAL_NORMALIZADA;

CREATE TABLE NOTA_FISCAL(
	NRO_NOTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NM_CLIENTE VARCHAR(256) NOT NULL,
    END_CLIENTE VARCHAR(256) NOT NULL,
    NM_VENDEDOR VARCHAR(256) NOT NULL,
    DT_EMISSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    VL_TOTAL FLOAT NOT NULL
    );
    
    CREATE TABLE PRODUTO(
    COD_PRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESC_PRODUTO VARCHAR(256) NOT NULL,
    UN_MED CHAR(2) NOT NULL,
    VL_PRODUTO FLOAT NOT NULL
    );
    
    CREATE TABLE ITEM_NOTA_FISCAL(
		NRO_NOTA INT NOT NULL,
        COD_PRODUTO INT NOT NULL,
        QTD_PRODUTO INT NOT NULL,
        VL_PRECO FLOAT NOT NULL,
        VL_TOTAL FLOAT NOT NULL,
        PRIMARY KEY(NRO_NOTA, COD_PRODUTO),
        CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL
			FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL(NRO_NOTA),
		CONSTRAINT FK_COD_PRODUTO_PRODUTO
			FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
            );